// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "ada.proto" (package "ada", syntax proto3)
// tslint:disable
//
// protobuf generated code shouldn't be here. consider add a script or a flag in main 
//
//
// generate:
// protoc -I$GOPATH/src:. --govalidators_out=:. --go_out=plugins=grpc:. ada.proto
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ADA } from "./ada";
import type { DashboardLogStatsReply } from "./ada";
import type { DashboardLogStatsReq } from "./ada";
import type { DashboardTrendsReply } from "./ada";
import type { DashboardTrendsReq } from "./ada";
import type { DashboardStatsReply } from "./ada";
import type { DashboardStatsReq } from "./ada";
import type { ListScanPluginReply } from "./ada";
import type { ListScanPluginReq } from "./ada";
import type { AddScanTmplReply } from "./ada";
import type { AddScanTmplReq } from "./ada";
import type { DeleteScanTmplReply } from "./ada";
import type { DeleteScanTmplReq } from "./ada";
import type { UpdateScanTmplReply } from "./ada";
import type { UpdateScanTmplReq } from "./ada";
import type { GetScanTmplReply } from "./ada";
import type { GetScanTmplReq } from "./ada";
import type { ListScanTmplReply } from "./ada";
import type { ListScanTmplReq } from "./ada";
import type { UpdateScanConfReply } from "./ada";
import type { UpdateScanConfReq } from "./ada";
import type { GetScanTmplNamesReply } from "./ada";
import type { GetScanTmplNamesReq } from "./ada";
import type { GetScanConfReply } from "./ada";
import type { GetScanConfReq } from "./ada";
import type { SetScanConfReply } from "./ada";
import type { SetScanConfReq } from "./ada";
import type { ListScanConfReply } from "./ada";
import type { ListScanConfReq } from "./ada";
import type { DeleteScanTaskReply } from "./ada";
import type { DeleteScanTaskReq } from "./ada";
import type { RecheckScanTaskReply } from "./ada";
import type { RecheckScanTaskReq } from "./ada";
import type { AddScanTaskReply } from "./ada";
import type { AddScanTaskReq } from "./ada";
import type { GetScanTaskReply } from "./ada";
import type { GetScanTaskReq } from "./ada";
import type { ListScanTaskReply } from "./ada";
import type { ListScanTaskReq } from "./ada";
import type { ListWeakPwdReply } from "./ada";
import type { ListWeakPwdReq } from "./ada";
import type { ListLeakReply } from "./ada";
import type { ListLeakReq } from "./ada";
import type { GetBaselineReply } from "./ada";
import type { GetBaselineReq } from "./ada";
import type { ListBaselineReply } from "./ada";
import type { ListBaselineReq } from "./ada";
import type { ScanRiskStatsReply } from "./ada";
import type { ScanRiskStatsReq } from "./ada";
import type { GetActivityRuleUniqueFieldsReply } from "./ada";
import type { GetActivityRuleUniqueFieldsReq } from "./ada";
import type { GetActivityRuleFieldsReply } from "./ada";
import type { GetActivityRuleFieldsReq } from "./ada";
import type { DeleteActivityRuleReply } from "./ada";
import type { DeleteActivityRuleReq } from "./ada";
import type { UpdateActivityRuleReply } from "./ada";
import type { UpdateActivityRuleReq } from "./ada";
import type { AddActivityRuleReply } from "./ada";
import type { AddActivityRuleReq } from "./ada";
import type { GetActivityRuleReply } from "./ada";
import type { GetActivityRuleReq } from "./ada";
import type { ListActivityRuleReply } from "./ada";
import type { ListActivityRuleReq } from "./ada";
import type { GetAlertRuleTagsReply } from "./ada";
import type { GetAlertRuleTagsReq } from "./ada";
import type { GetAlertTypesReply } from "./ada";
import type { GetAlertTypesReq } from "./ada";
import type { GetAlertRuleNamesReply } from "./ada";
import type { GetAlertRuleNamesReq } from "./ada";
import type { DeleteAlertRuleReply } from "./ada";
import type { DeleteAlertRuleReq } from "./ada";
import type { UpdateAlertRuleReply } from "./ada";
import type { UpdateAlertRuleReq } from "./ada";
import type { AddAlertRuleReply } from "./ada";
import type { AddAlertRuleReq } from "./ada";
import type { ListAlertRuleReply } from "./ada";
import type { ListAlertRuleReq } from "./ada";
import type { DeleteThreatBlockReply } from "./ada";
import type { DeleteThreatBlockReq } from "./ada";
import type { UpdateThreatBlockReply } from "./ada";
import type { UpdateThreatBlockReq } from "./ada";
import type { AddThreatBlockReply } from "./ada";
import type { AddThreatBlockReq } from "./ada";
import type { ListThreatBlockReply } from "./ada";
import type { ListThreatBlockReq } from "./ada";
import type { DeleteThreatWhitelistReply } from "./ada";
import type { DeleteThreatWhitelistReq } from "./ada";
import type { UpdateThreatWhitelistReply } from "./ada";
import type { UpdateThreatWhitelistReq } from "./ada";
import type { AddThreatWhitelistReply } from "./ada";
import type { AddThreatWhitelistReq } from "./ada";
import type { GetThreatWhitelistFieldReply } from "./ada";
import type { GetThreatWhitelistFieldReq } from "./ada";
import type { ListThreatWhitelistReply } from "./ada";
import type { ListThreatWhitelistReq } from "./ada";
import type { DeleteSensitiveEntryReply } from "./ada";
import type { DeleteSensitiveEntryReq } from "./ada";
import type { ListDomainEntryReply } from "./ada";
import type { ListDomainEntryReq } from "./ada";
import type { AddSensitiveEntryReply } from "./ada";
import type { AddSensitiveEntryReq } from "./ada";
import type { ListSensitiveEntryReply } from "./ada";
import type { ListSensitiveEntryReq } from "./ada";
import type { GetActivityReply } from "./ada";
import type { GetActivityReq } from "./ada";
import type { GetActivityNamesReply } from "./ada";
import type { GetActivityNamesReq } from "./ada";
import type { ListActivityReply } from "./ada";
import type { ListActivityReq } from "./ada";
import type { ActionThreatReply } from "./ada";
import type { ActionThreatReq } from "./ada";
import type { GetThreatReply } from "./ada";
import type { GetThreatReq } from "./ada";
import type { GetThreatNamesReply } from "./ada";
import type { GetThreatNamesReq } from "./ada";
import type { ListThreatReply } from "./ada";
import type { ListThreatReq } from "./ada";
import type { ThreatTrendsReply } from "./ada";
import type { ThreatTrendsReq } from "./ada";
import type { ThreatTopsReply } from "./ada";
import type { ThreatTopsReq } from "./ada";
import type { ListSystemLogsReply } from "./ada";
import type { ListSystemLogsReq } from "./ada";
import type { ListAuditLogReply } from "./ada";
import type { ListAuditLogReq } from "./ada";
import type { StatsNotifyReply } from "./ada";
import type { StatsNotifyReq } from "./ada";
import type { UpdateNotifyReply } from "./ada";
import type { UpdateNotifyReq } from "./ada";
import type { ListNotifyReply } from "./ada";
import type { ListNotifyReq } from "./ada";
import type { DeleteExportTaskReply } from "./ada";
import type { DeleteExportTaskReq } from "./ada";
import type { AddExportTaskReply } from "./ada";
import type { AddExportTaskReq } from "./ada";
import type { ListExportTaskReply } from "./ada";
import type { ListExportTaskReq } from "./ada";
import type { TestNotifyConfReply } from "./ada";
import type { TestNotifyConfReq } from "./ada";
import type { EnableNotifyConfReply } from "./ada";
import type { EnableNotifyConfReq } from "./ada";
import type { UpdateNotifyConfReply } from "./ada";
import type { UpdateNotifyConfReq } from "./ada";
import type { ListNotifyConfReply } from "./ada";
import type { ListNotifyConfReq } from "./ada";
import type { NetworkDebugReply } from "./ada";
import type { NetworkDebugReq } from "./ada";
import type { UpdateLicenseReply } from "./ada";
import type { UpdateLicenseReq } from "./ada";
import type { GetLicenseReply } from "./ada";
import type { GetLicenseReq } from "./ada";
import type { SetSystemStatsCfgReply } from "./ada";
import type { SetSystemStatsCfgReq } from "./ada";
import type { GetSystemStatsReply } from "./ada";
import type { GetSystemStatsReq } from "./ada";
import type { UpdateSystemCfgReply } from "./ada";
import type { UpdateSystemCfgReq } from "./ada";
import type { UpdateSystemLanguageReply } from "./ada";
import type { UpdateSystemLanguageReq } from "./ada";
import type { GetSystemIconReply } from "./ada";
import type { GetSystemIconReq } from "./ada";
import type { GetSystemInfoReply } from "./ada";
import type { GetSystemInfoReq } from "./ada";
import type { UpdateSensorVersionReply } from "./ada";
import type { UpdateSensorVersionReq } from "./ada";
import type { CmdSensorReply } from "./ada";
import type { CmdSensorReq } from "./ada";
import type { DownloadSensorReply } from "./ada";
import type { DownloadSensorReq } from "./ada";
import type { UpdateSensorReply } from "./ada";
import type { UpdateSensorReq } from "./ada";
import type { ListSensorReply } from "./ada";
import type { ListSensorReq } from "./ada";
import type { DeploySensorReply } from "./ada";
import type { DeploySensorReq } from "./ada";
import type { UpdateDomainDataReply } from "./ada";
import type { UpdateDomainDataReq } from "./ada";
import type { DeleteDomainReply } from "./ada";
import type { DeleteDomainReq } from "./ada";
import type { UpdateDomainReply } from "./ada";
import type { UpdateDomainReq } from "./ada";
import type { TestDomainReply } from "./ada";
import type { TestDomainReq } from "./ada";
import type { AddDomainReply } from "./ada";
import type { AddDomainReq } from "./ada";
import type { ListDomainReply } from "./ada";
import type { ListDomainReq } from "./ada";
import type { GetPwdUpdateTmReply } from "./ada";
import type { GetPwdUpdateTmReq } from "./ada";
import type { ResetPasswordReply } from "./ada";
import type { ResetPasswordReq } from "./ada";
import type { UpdateAvatarReply } from "./ada";
import type { UpdateAvatarReq } from "./ada";
import type { DisableMfaReply } from "./ada";
import type { DisableMfaReq } from "./ada";
import type { EnableMfaReply } from "./ada";
import type { EnableMfaReq } from "./ada";
import type { CheckMfaReply } from "./ada";
import type { CheckMfaReq } from "./ada";
import type { UserExistsReply } from "./ada";
import type { UserExistsReq } from "./ada";
import type { DeleteUserReply } from "./ada";
import type { DeleteUserReq } from "./ada";
import type { UpdateUserPasswordReply } from "./ada";
import type { UpdateUserPasswordReq } from "./ada";
import type { UpdateUserReply } from "./ada";
import type { UpdateUserReq } from "./ada";
import type { AddUserReply } from "./ada";
import type { AddUserReq } from "./ada";
import type { ListUserReply } from "./ada";
import type { ListUserReq } from "./ada";
import type { LogoutReply } from "./ada";
import type { LogoutReq } from "./ada";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { LoginReply } from "./ada";
import type { LoginReq } from "./ada";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
// import "github.com/mwitkow/go-proto-validators/validator.proto";

/**
 * @generated from protobuf service ada.ADA
 */
export interface IADAClient {
    /**
     * User 账户管理
     *
     * @generated from protobuf rpc: Login(ada.LoginReq) returns (ada.LoginReply);
     */
    login(input: LoginReq, options?: RpcOptions): UnaryCall<LoginReq, LoginReply>;
    /**
     * @generated from protobuf rpc: Logout(ada.LogoutReq) returns (ada.LogoutReply);
     */
    logout(input: LogoutReq, options?: RpcOptions): UnaryCall<LogoutReq, LogoutReply>;
    /**
     * @generated from protobuf rpc: ListUser(ada.ListUserReq) returns (ada.ListUserReply);
     */
    listUser(input: ListUserReq, options?: RpcOptions): UnaryCall<ListUserReq, ListUserReply>;
    /**
     * @generated from protobuf rpc: AddUser(ada.AddUserReq) returns (ada.AddUserReply);
     */
    addUser(input: AddUserReq, options?: RpcOptions): UnaryCall<AddUserReq, AddUserReply>;
    /**
     * @generated from protobuf rpc: UpdateUser(ada.UpdateUserReq) returns (ada.UpdateUserReply);
     */
    updateUser(input: UpdateUserReq, options?: RpcOptions): UnaryCall<UpdateUserReq, UpdateUserReply>;
    /**
     * @generated from protobuf rpc: UpdateUserPassword(ada.UpdateUserPasswordReq) returns (ada.UpdateUserPasswordReply);
     */
    updateUserPassword(input: UpdateUserPasswordReq, options?: RpcOptions): UnaryCall<UpdateUserPasswordReq, UpdateUserPasswordReply>;
    /**
     * @generated from protobuf rpc: DeleteUser(ada.DeleteUserReq) returns (ada.DeleteUserReply);
     */
    deleteUser(input: DeleteUserReq, options?: RpcOptions): UnaryCall<DeleteUserReq, DeleteUserReply>;
    /**
     * @generated from protobuf rpc: UserExists(ada.UserExistsReq) returns (ada.UserExistsReply);
     */
    userExists(input: UserExistsReq, options?: RpcOptions): UnaryCall<UserExistsReq, UserExistsReply>;
    /**
     * Authority 二次验证相关接口
     *
     * @generated from protobuf rpc: CheckMfa(ada.CheckMfaReq) returns (ada.CheckMfaReply);
     */
    checkMfa(input: CheckMfaReq, options?: RpcOptions): UnaryCall<CheckMfaReq, CheckMfaReply>;
    /**
     * @generated from protobuf rpc: EnableMfa(ada.EnableMfaReq) returns (ada.EnableMfaReply);
     */
    enableMfa(input: EnableMfaReq, options?: RpcOptions): UnaryCall<EnableMfaReq, EnableMfaReply>;
    /**
     * @generated from protobuf rpc: DisableMfa(ada.DisableMfaReq) returns (ada.DisableMfaReply);
     */
    disableMfa(input: DisableMfaReq, options?: RpcOptions): UnaryCall<DisableMfaReq, DisableMfaReply>;
    /**
     * @generated from protobuf rpc: UpdateAvatar(ada.UpdateAvatarReq) returns (ada.UpdateAvatarReply);
     */
    updateAvatar(input: UpdateAvatarReq, options?: RpcOptions): UnaryCall<UpdateAvatarReq, UpdateAvatarReply>;
    /**
     * @generated from protobuf rpc: ResetPassword(ada.ResetPasswordReq) returns (ada.ResetPasswordReply);
     */
    resetPassword(input: ResetPasswordReq, options?: RpcOptions): UnaryCall<ResetPasswordReq, ResetPasswordReply>;
    /**
     * @generated from protobuf rpc: GetPwdUpdateTm(ada.GetPwdUpdateTmReq) returns (ada.GetPwdUpdateTmReply);
     */
    getPwdUpdateTm(input: GetPwdUpdateTmReq, options?: RpcOptions): UnaryCall<GetPwdUpdateTmReq, GetPwdUpdateTmReply>;
    /**
     * Domain
     *
     * @generated from protobuf rpc: ListDomain(ada.ListDomainReq) returns (ada.ListDomainReply);
     */
    listDomain(input: ListDomainReq, options?: RpcOptions): UnaryCall<ListDomainReq, ListDomainReply>;
    /**
     * @generated from protobuf rpc: AddDomain(ada.AddDomainReq) returns (ada.AddDomainReply);
     */
    addDomain(input: AddDomainReq, options?: RpcOptions): UnaryCall<AddDomainReq, AddDomainReply>;
    /**
     * @generated from protobuf rpc: TestDomain(ada.TestDomainReq) returns (ada.TestDomainReply);
     */
    testDomain(input: TestDomainReq, options?: RpcOptions): UnaryCall<TestDomainReq, TestDomainReply>;
    /**
     * @generated from protobuf rpc: UpdateDomain(ada.UpdateDomainReq) returns (ada.UpdateDomainReply);
     */
    updateDomain(input: UpdateDomainReq, options?: RpcOptions): UnaryCall<UpdateDomainReq, UpdateDomainReply>;
    /**
     * @generated from protobuf rpc: DeleteDomain(ada.DeleteDomainReq) returns (ada.DeleteDomainReply);
     */
    deleteDomain(input: DeleteDomainReq, options?: RpcOptions): UnaryCall<DeleteDomainReq, DeleteDomainReply>;
    /**
     * @generated from protobuf rpc: UpdateDomainData(ada.UpdateDomainDataReq) returns (ada.UpdateDomainDataReply);
     */
    updateDomainData(input: UpdateDomainDataReq, options?: RpcOptions): UnaryCall<UpdateDomainDataReq, UpdateDomainDataReply>;
    /**
     * @generated from protobuf rpc: DeploySensor(ada.DeploySensorReq) returns (ada.DeploySensorReply);
     */
    deploySensor(input: DeploySensorReq, options?: RpcOptions): UnaryCall<DeploySensorReq, DeploySensorReply>;
    /**
     * sensor
     *
     * @generated from protobuf rpc: ListSensor(ada.ListSensorReq) returns (ada.ListSensorReply);
     */
    listSensor(input: ListSensorReq, options?: RpcOptions): UnaryCall<ListSensorReq, ListSensorReply>;
    /**
     * @generated from protobuf rpc: UpdateSensor(ada.UpdateSensorReq) returns (ada.UpdateSensorReply);
     */
    updateSensor(input: UpdateSensorReq, options?: RpcOptions): UnaryCall<UpdateSensorReq, UpdateSensorReply>;
    /**
     * @generated from protobuf rpc: DownloadSensor(ada.DownloadSensorReq) returns (ada.DownloadSensorReply);
     */
    downloadSensor(input: DownloadSensorReq, options?: RpcOptions): UnaryCall<DownloadSensorReq, DownloadSensorReply>;
    /**
     * @generated from protobuf rpc: CmdSensor(ada.CmdSensorReq) returns (ada.CmdSensorReply);
     */
    cmdSensor(input: CmdSensorReq, options?: RpcOptions): UnaryCall<CmdSensorReq, CmdSensorReply>;
    /**
     * @generated from protobuf rpc: UpdateSensorVersion(ada.UpdateSensorVersionReq) returns (ada.UpdateSensorVersionReply);
     */
    updateSensorVersion(input: UpdateSensorVersionReq, options?: RpcOptions): UnaryCall<UpdateSensorVersionReq, UpdateSensorVersionReply>;
    /**
     * 系统信息
     * 1.基本信息
     *
     * @generated from protobuf rpc: GetSystemInfo(ada.GetSystemInfoReq) returns (ada.GetSystemInfoReply);
     */
    getSystemInfo(input: GetSystemInfoReq, options?: RpcOptions): UnaryCall<GetSystemInfoReq, GetSystemInfoReply>;
    /**
     * @generated from protobuf rpc: GetSystemIcon(ada.GetSystemIconReq) returns (ada.GetSystemIconReply);
     */
    getSystemIcon(input: GetSystemIconReq, options?: RpcOptions): UnaryCall<GetSystemIconReq, GetSystemIconReply>;
    /**
     * @generated from protobuf rpc: UpdateSystemLanguage(ada.UpdateSystemLanguageReq) returns (ada.UpdateSystemLanguageReply);
     */
    updateSystemLanguage(input: UpdateSystemLanguageReq, options?: RpcOptions): UnaryCall<UpdateSystemLanguageReq, UpdateSystemLanguageReply>;
    /**
     * @generated from protobuf rpc: UpdateSystemCfg(ada.UpdateSystemCfgReq) returns (ada.UpdateSystemCfgReply);
     */
    updateSystemCfg(input: UpdateSystemCfgReq, options?: RpcOptions): UnaryCall<UpdateSystemCfgReq, UpdateSystemCfgReply>;
    /**
     * 2.系统监控: load|cpu|mem|net_rx|net_tx
     *
     * @generated from protobuf rpc: GetSystemStats(ada.GetSystemStatsReq) returns (ada.GetSystemStatsReply);
     */
    getSystemStats(input: GetSystemStatsReq, options?: RpcOptions): UnaryCall<GetSystemStatsReq, GetSystemStatsReply>;
    /**
     * @generated from protobuf rpc: SetSystemStatsCfg(ada.SetSystemStatsCfgReq) returns (ada.SetSystemStatsCfgReply);
     */
    setSystemStatsCfg(input: SetSystemStatsCfgReq, options?: RpcOptions): UnaryCall<SetSystemStatsCfgReq, SetSystemStatsCfgReply>;
    /**
     * 3.授权管理
     *
     * @generated from protobuf rpc: GetLicense(ada.GetLicenseReq) returns (ada.GetLicenseReply);
     */
    getLicense(input: GetLicenseReq, options?: RpcOptions): UnaryCall<GetLicenseReq, GetLicenseReply>;
    /**
     * @generated from protobuf rpc: UpdateLicense(ada.UpdateLicenseReq) returns (ada.UpdateLicenseReply);
     */
    updateLicense(input: UpdateLicenseReq, options?: RpcOptions): UnaryCall<UpdateLicenseReq, UpdateLicenseReply>;
    /**
     * 4.调试工具
     *
     * @generated from protobuf rpc: NetworkDebug(ada.NetworkDebugReq) returns (ada.NetworkDebugReply);
     */
    networkDebug(input: NetworkDebugReq, options?: RpcOptions): UnaryCall<NetworkDebugReq, NetworkDebugReply>;
    /**
     * 告警配置
     *
     * @generated from protobuf rpc: ListNotifyConf(ada.ListNotifyConfReq) returns (ada.ListNotifyConfReply);
     */
    listNotifyConf(input: ListNotifyConfReq, options?: RpcOptions): UnaryCall<ListNotifyConfReq, ListNotifyConfReply>;
    /**
     * @generated from protobuf rpc: UpdateNotifyConf(ada.UpdateNotifyConfReq) returns (ada.UpdateNotifyConfReply);
     */
    updateNotifyConf(input: UpdateNotifyConfReq, options?: RpcOptions): UnaryCall<UpdateNotifyConfReq, UpdateNotifyConfReply>;
    /**
     * @generated from protobuf rpc: EnableNotifyConf(ada.EnableNotifyConfReq) returns (ada.EnableNotifyConfReply);
     */
    enableNotifyConf(input: EnableNotifyConfReq, options?: RpcOptions): UnaryCall<EnableNotifyConfReq, EnableNotifyConfReply>;
    /**
     * @generated from protobuf rpc: TestNotifyConf(ada.TestNotifyConfReq) returns (ada.TestNotifyConfReply);
     */
    testNotifyConf(input: TestNotifyConfReq, options?: RpcOptions): UnaryCall<TestNotifyConfReq, TestNotifyConfReply>;
    /**
     * 导出管理
     *
     * @generated from protobuf rpc: ListExportTask(ada.ListExportTaskReq) returns (ada.ListExportTaskReply);
     */
    listExportTask(input: ListExportTaskReq, options?: RpcOptions): UnaryCall<ListExportTaskReq, ListExportTaskReply>;
    /**
     * @generated from protobuf rpc: AddExportTask(ada.AddExportTaskReq) returns (ada.AddExportTaskReply);
     */
    addExportTask(input: AddExportTaskReq, options?: RpcOptions): UnaryCall<AddExportTaskReq, AddExportTaskReply>;
    /**
     * @generated from protobuf rpc: DeleteExportTask(ada.DeleteExportTaskReq) returns (ada.DeleteExportTaskReply);
     */
    deleteExportTask(input: DeleteExportTaskReq, options?: RpcOptions): UnaryCall<DeleteExportTaskReq, DeleteExportTaskReply>;
    /**
     * 消息中心
     *
     * @generated from protobuf rpc: ListNotify(ada.ListNotifyReq) returns (ada.ListNotifyReply);
     */
    listNotify(input: ListNotifyReq, options?: RpcOptions): UnaryCall<ListNotifyReq, ListNotifyReply>;
    /**
     * @generated from protobuf rpc: UpdateNotify(ada.UpdateNotifyReq) returns (ada.UpdateNotifyReply);
     */
    updateNotify(input: UpdateNotifyReq, options?: RpcOptions): UnaryCall<UpdateNotifyReq, UpdateNotifyReply>;
    /**
     * @generated from protobuf rpc: StatsNotify(ada.StatsNotifyReq) returns (ada.StatsNotifyReply);
     */
    statsNotify(input: StatsNotifyReq, options?: RpcOptions): UnaryCall<StatsNotifyReq, StatsNotifyReply>;
    /**
     * 日志审计
     *
     * @generated from protobuf rpc: ListAuditLog(ada.ListAuditLogReq) returns (ada.ListAuditLogReply);
     */
    listAuditLog(input: ListAuditLogReq, options?: RpcOptions): UnaryCall<ListAuditLogReq, ListAuditLogReply>;
    /**
     * 系统日志
     *
     * @generated from protobuf rpc: ListSystemLogs(ada.ListSystemLogsReq) returns (ada.ListSystemLogsReply);
     */
    listSystemLogs(input: ListSystemLogsReq, options?: RpcOptions): UnaryCall<ListSystemLogsReq, ListSystemLogsReply>;
    /**
     * //////////////////////////////
     * threat威胁检测dashboard
     *
     * @generated from protobuf rpc: ThreatTops(ada.ThreatTopsReq) returns (ada.ThreatTopsReply);
     */
    threatTops(input: ThreatTopsReq, options?: RpcOptions): UnaryCall<ThreatTopsReq, ThreatTopsReply>;
    /**
     * @generated from protobuf rpc: ThreatTrends(ada.ThreatTrendsReq) returns (ada.ThreatTrendsReply);
     */
    threatTrends(input: ThreatTrendsReq, options?: RpcOptions): UnaryCall<ThreatTrendsReq, ThreatTrendsReply>;
    /**
     * threat威胁检测
     *
     * @generated from protobuf rpc: ListThreat(ada.ListThreatReq) returns (ada.ListThreatReply);
     */
    listThreat(input: ListThreatReq, options?: RpcOptions): UnaryCall<ListThreatReq, ListThreatReply>;
    /**
     * @generated from protobuf rpc: GetThreatNames(ada.GetThreatNamesReq) returns (ada.GetThreatNamesReply);
     */
    getThreatNames(input: GetThreatNamesReq, options?: RpcOptions): UnaryCall<GetThreatNamesReq, GetThreatNamesReply>;
    /**
     * @generated from protobuf rpc: GetThreat(ada.GetThreatReq) returns (ada.GetThreatReply);
     */
    getThreat(input: GetThreatReq, options?: RpcOptions): UnaryCall<GetThreatReq, GetThreatReply>;
    /**
     * @generated from protobuf rpc: ActionThreat(ada.ActionThreatReq) returns (ada.ActionThreatReply);
     */
    actionThreat(input: ActionThreatReq, options?: RpcOptions): UnaryCall<ActionThreatReq, ActionThreatReply>;
    /**
     * @generated from protobuf rpc: ListActivity(ada.ListActivityReq) returns (ada.ListActivityReply);
     */
    listActivity(input: ListActivityReq, options?: RpcOptions): UnaryCall<ListActivityReq, ListActivityReply>;
    /**
     * @generated from protobuf rpc: GetActivityNames(ada.GetActivityNamesReq) returns (ada.GetActivityNamesReply);
     */
    getActivityNames(input: GetActivityNamesReq, options?: RpcOptions): UnaryCall<GetActivityNamesReq, GetActivityNamesReply>;
    /**
     * @generated from protobuf rpc: GetActivity(ada.GetActivityReq) returns (ada.GetActivityReply);
     */
    getActivity(input: GetActivityReq, options?: RpcOptions): UnaryCall<GetActivityReq, GetActivityReply>;
    /**
     * @generated from protobuf rpc: ListSensitiveEntry(ada.ListSensitiveEntryReq) returns (ada.ListSensitiveEntryReply);
     */
    listSensitiveEntry(input: ListSensitiveEntryReq, options?: RpcOptions): UnaryCall<ListSensitiveEntryReq, ListSensitiveEntryReply>;
    /**
     * @generated from protobuf rpc: AddSensitiveEntry(ada.AddSensitiveEntryReq) returns (ada.AddSensitiveEntryReply);
     */
    addSensitiveEntry(input: AddSensitiveEntryReq, options?: RpcOptions): UnaryCall<AddSensitiveEntryReq, AddSensitiveEntryReply>;
    /**
     * @generated from protobuf rpc: ListDomainEntry(ada.ListDomainEntryReq) returns (ada.ListDomainEntryReply);
     */
    listDomainEntry(input: ListDomainEntryReq, options?: RpcOptions): UnaryCall<ListDomainEntryReq, ListDomainEntryReply>;
    /**
     * @generated from protobuf rpc: DeleteSensitiveEntry(ada.DeleteSensitiveEntryReq) returns (ada.DeleteSensitiveEntryReply);
     */
    deleteSensitiveEntry(input: DeleteSensitiveEntryReq, options?: RpcOptions): UnaryCall<DeleteSensitiveEntryReq, DeleteSensitiveEntryReply>;
    /**
     * @generated from protobuf rpc: ListThreatWhitelist(ada.ListThreatWhitelistReq) returns (ada.ListThreatWhitelistReply);
     */
    listThreatWhitelist(input: ListThreatWhitelistReq, options?: RpcOptions): UnaryCall<ListThreatWhitelistReq, ListThreatWhitelistReply>;
    /**
     * @generated from protobuf rpc: GetThreatWhitelistField(ada.GetThreatWhitelistFieldReq) returns (ada.GetThreatWhitelistFieldReply);
     */
    getThreatWhitelistField(input: GetThreatWhitelistFieldReq, options?: RpcOptions): UnaryCall<GetThreatWhitelistFieldReq, GetThreatWhitelistFieldReply>;
    /**
     * @generated from protobuf rpc: AddThreatWhitelist(ada.AddThreatWhitelistReq) returns (ada.AddThreatWhitelistReply);
     */
    addThreatWhitelist(input: AddThreatWhitelistReq, options?: RpcOptions): UnaryCall<AddThreatWhitelistReq, AddThreatWhitelistReply>;
    /**
     * @generated from protobuf rpc: UpdateThreatWhitelist(ada.UpdateThreatWhitelistReq) returns (ada.UpdateThreatWhitelistReply);
     */
    updateThreatWhitelist(input: UpdateThreatWhitelistReq, options?: RpcOptions): UnaryCall<UpdateThreatWhitelistReq, UpdateThreatWhitelistReply>;
    /**
     * @generated from protobuf rpc: DeleteThreatWhitelist(ada.DeleteThreatWhitelistReq) returns (ada.DeleteThreatWhitelistReply);
     */
    deleteThreatWhitelist(input: DeleteThreatWhitelistReq, options?: RpcOptions): UnaryCall<DeleteThreatWhitelistReq, DeleteThreatWhitelistReply>;
    /**
     * @generated from protobuf rpc: ListThreatBlock(ada.ListThreatBlockReq) returns (ada.ListThreatBlockReply);
     */
    listThreatBlock(input: ListThreatBlockReq, options?: RpcOptions): UnaryCall<ListThreatBlockReq, ListThreatBlockReply>;
    /**
     * @generated from protobuf rpc: AddThreatBlock(ada.AddThreatBlockReq) returns (ada.AddThreatBlockReply);
     */
    addThreatBlock(input: AddThreatBlockReq, options?: RpcOptions): UnaryCall<AddThreatBlockReq, AddThreatBlockReply>;
    /**
     * @generated from protobuf rpc: UpdateThreatBlock(ada.UpdateThreatBlockReq) returns (ada.UpdateThreatBlockReply);
     */
    updateThreatBlock(input: UpdateThreatBlockReq, options?: RpcOptions): UnaryCall<UpdateThreatBlockReq, UpdateThreatBlockReply>;
    /**
     * @generated from protobuf rpc: DeleteThreatBlock(ada.DeleteThreatBlockReq) returns (ada.DeleteThreatBlockReply);
     */
    deleteThreatBlock(input: DeleteThreatBlockReq, options?: RpcOptions): UnaryCall<DeleteThreatBlockReq, DeleteThreatBlockReply>;
    /**
     * Rule Management (Alert Rules & Activity Rules)
     *
     * @generated from protobuf rpc: ListAlertRule(ada.ListAlertRuleReq) returns (ada.ListAlertRuleReply);
     */
    listAlertRule(input: ListAlertRuleReq, options?: RpcOptions): UnaryCall<ListAlertRuleReq, ListAlertRuleReply>;
    /**
     * @generated from protobuf rpc: AddAlertRule(ada.AddAlertRuleReq) returns (ada.AddAlertRuleReply);
     */
    addAlertRule(input: AddAlertRuleReq, options?: RpcOptions): UnaryCall<AddAlertRuleReq, AddAlertRuleReply>;
    /**
     * @generated from protobuf rpc: UpdateAlertRule(ada.UpdateAlertRuleReq) returns (ada.UpdateAlertRuleReply);
     */
    updateAlertRule(input: UpdateAlertRuleReq, options?: RpcOptions): UnaryCall<UpdateAlertRuleReq, UpdateAlertRuleReply>;
    /**
     * @generated from protobuf rpc: DeleteAlertRule(ada.DeleteAlertRuleReq) returns (ada.DeleteAlertRuleReply);
     */
    deleteAlertRule(input: DeleteAlertRuleReq, options?: RpcOptions): UnaryCall<DeleteAlertRuleReq, DeleteAlertRuleReply>;
    /**
     * @generated from protobuf rpc: GetAlertRuleNames(ada.GetAlertRuleNamesReq) returns (ada.GetAlertRuleNamesReply);
     */
    getAlertRuleNames(input: GetAlertRuleNamesReq, options?: RpcOptions): UnaryCall<GetAlertRuleNamesReq, GetAlertRuleNamesReply>;
    /**
     * @generated from protobuf rpc: GetAlertTypes(ada.GetAlertTypesReq) returns (ada.GetAlertTypesReply);
     */
    getAlertTypes(input: GetAlertTypesReq, options?: RpcOptions): UnaryCall<GetAlertTypesReq, GetAlertTypesReply>;
    /**
     * @generated from protobuf rpc: GetAlertRuleTags(ada.GetAlertRuleTagsReq) returns (ada.GetAlertRuleTagsReply);
     */
    getAlertRuleTags(input: GetAlertRuleTagsReq, options?: RpcOptions): UnaryCall<GetAlertRuleTagsReq, GetAlertRuleTagsReply>;
    /**
     * @generated from protobuf rpc: ListActivityRule(ada.ListActivityRuleReq) returns (ada.ListActivityRuleReply);
     */
    listActivityRule(input: ListActivityRuleReq, options?: RpcOptions): UnaryCall<ListActivityRuleReq, ListActivityRuleReply>;
    /**
     * @generated from protobuf rpc: GetActivityRule(ada.GetActivityRuleReq) returns (ada.GetActivityRuleReply);
     */
    getActivityRule(input: GetActivityRuleReq, options?: RpcOptions): UnaryCall<GetActivityRuleReq, GetActivityRuleReply>;
    /**
     * @generated from protobuf rpc: AddActivityRule(ada.AddActivityRuleReq) returns (ada.AddActivityRuleReply);
     */
    addActivityRule(input: AddActivityRuleReq, options?: RpcOptions): UnaryCall<AddActivityRuleReq, AddActivityRuleReply>;
    /**
     * @generated from protobuf rpc: UpdateActivityRule(ada.UpdateActivityRuleReq) returns (ada.UpdateActivityRuleReply);
     */
    updateActivityRule(input: UpdateActivityRuleReq, options?: RpcOptions): UnaryCall<UpdateActivityRuleReq, UpdateActivityRuleReply>;
    /**
     * @generated from protobuf rpc: DeleteActivityRule(ada.DeleteActivityRuleReq) returns (ada.DeleteActivityRuleReply);
     */
    deleteActivityRule(input: DeleteActivityRuleReq, options?: RpcOptions): UnaryCall<DeleteActivityRuleReq, DeleteActivityRuleReply>;
    /**
     * @generated from protobuf rpc: GetActivityRuleFields(ada.GetActivityRuleFieldsReq) returns (ada.GetActivityRuleFieldsReply);
     */
    getActivityRuleFields(input: GetActivityRuleFieldsReq, options?: RpcOptions): UnaryCall<GetActivityRuleFieldsReq, GetActivityRuleFieldsReply>;
    /**
     * @generated from protobuf rpc: GetActivityRuleUniqueFields(ada.GetActivityRuleUniqueFieldsReq) returns (ada.GetActivityRuleUniqueFieldsReply);
     */
    getActivityRuleUniqueFields(input: GetActivityRuleUniqueFieldsReq, options?: RpcOptions): UnaryCall<GetActivityRuleUniqueFieldsReq, GetActivityRuleUniqueFieldsReply>;
    /**
     * //////////////////////////////
     * scanrisk主动检测dashboard
     *
     * @generated from protobuf rpc: ScanRiskStats(ada.ScanRiskStatsReq) returns (ada.ScanRiskStatsReply);
     */
    scanRiskStats(input: ScanRiskStatsReq, options?: RpcOptions): UnaryCall<ScanRiskStatsReq, ScanRiskStatsReply>;
    /**
     * scanrisk主动检测
     *
     * @generated from protobuf rpc: ListBaseline(ada.ListBaselineReq) returns (ada.ListBaselineReply);
     */
    listBaseline(input: ListBaselineReq, options?: RpcOptions): UnaryCall<ListBaselineReq, ListBaselineReply>;
    /**
     * @generated from protobuf rpc: GetBaseline(ada.GetBaselineReq) returns (ada.GetBaselineReply);
     */
    getBaseline(input: GetBaselineReq, options?: RpcOptions): UnaryCall<GetBaselineReq, GetBaselineReply>;
    /**
     * @generated from protobuf rpc: ListLeak(ada.ListLeakReq) returns (ada.ListLeakReply);
     */
    listLeak(input: ListLeakReq, options?: RpcOptions): UnaryCall<ListLeakReq, ListLeakReply>;
    /**
     * @generated from protobuf rpc: ListWeakPwd(ada.ListWeakPwdReq) returns (ada.ListWeakPwdReply);
     */
    listWeakPwd(input: ListWeakPwdReq, options?: RpcOptions): UnaryCall<ListWeakPwdReq, ListWeakPwdReply>;
    /**
     * 任务管理
     *
     * @generated from protobuf rpc: ListScanTask(ada.ListScanTaskReq) returns (ada.ListScanTaskReply);
     */
    listScanTask(input: ListScanTaskReq, options?: RpcOptions): UnaryCall<ListScanTaskReq, ListScanTaskReply>;
    /**
     * @generated from protobuf rpc: GetScanTask(ada.GetScanTaskReq) returns (ada.GetScanTaskReply);
     */
    getScanTask(input: GetScanTaskReq, options?: RpcOptions): UnaryCall<GetScanTaskReq, GetScanTaskReply>;
    /**
     * @generated from protobuf rpc: AddScanTask(ada.AddScanTaskReq) returns (ada.AddScanTaskReply);
     */
    addScanTask(input: AddScanTaskReq, options?: RpcOptions): UnaryCall<AddScanTaskReq, AddScanTaskReply>;
    /**
     * @generated from protobuf rpc: RecheckScanTask(ada.RecheckScanTaskReq) returns (ada.RecheckScanTaskReply);
     */
    recheckScanTask(input: RecheckScanTaskReq, options?: RpcOptions): UnaryCall<RecheckScanTaskReq, RecheckScanTaskReply>;
    /**
     * @generated from protobuf rpc: DeleteScanTask(ada.DeleteScanTaskReq) returns (ada.DeleteScanTaskReply);
     */
    deleteScanTask(input: DeleteScanTaskReq, options?: RpcOptions): UnaryCall<DeleteScanTaskReq, DeleteScanTaskReply>;
    /**
     * 扫描配置
     *
     * @generated from protobuf rpc: ListScanConf(ada.ListScanConfReq) returns (ada.ListScanConfReply);
     */
    listScanConf(input: ListScanConfReq, options?: RpcOptions): UnaryCall<ListScanConfReq, ListScanConfReply>;
    /**
     * @generated from protobuf rpc: SetScanConf(ada.SetScanConfReq) returns (ada.SetScanConfReply);
     */
    setScanConf(input: SetScanConfReq, options?: RpcOptions): UnaryCall<SetScanConfReq, SetScanConfReply>;
    /**
     * @generated from protobuf rpc: GetScanConf(ada.GetScanConfReq) returns (ada.GetScanConfReply);
     */
    getScanConf(input: GetScanConfReq, options?: RpcOptions): UnaryCall<GetScanConfReq, GetScanConfReply>;
    /**
     * @generated from protobuf rpc: GetScanTmplNames(ada.GetScanTmplNamesReq) returns (ada.GetScanTmplNamesReply);
     */
    getScanTmplNames(input: GetScanTmplNamesReq, options?: RpcOptions): UnaryCall<GetScanTmplNamesReq, GetScanTmplNamesReply>;
    /**
     * @generated from protobuf rpc: UpdateScanConf(ada.UpdateScanConfReq) returns (ada.UpdateScanConfReply);
     */
    updateScanConf(input: UpdateScanConfReq, options?: RpcOptions): UnaryCall<UpdateScanConfReq, UpdateScanConfReply>;
    /**
     * 扫描模板
     *
     * @generated from protobuf rpc: ListScanTmpl(ada.ListScanTmplReq) returns (ada.ListScanTmplReply);
     */
    listScanTmpl(input: ListScanTmplReq, options?: RpcOptions): UnaryCall<ListScanTmplReq, ListScanTmplReply>;
    /**
     * @generated from protobuf rpc: GetScanTmpl(ada.GetScanTmplReq) returns (ada.GetScanTmplReply);
     */
    getScanTmpl(input: GetScanTmplReq, options?: RpcOptions): UnaryCall<GetScanTmplReq, GetScanTmplReply>;
    /**
     * @generated from protobuf rpc: UpdateScanTmpl(ada.UpdateScanTmplReq) returns (ada.UpdateScanTmplReply);
     */
    updateScanTmpl(input: UpdateScanTmplReq, options?: RpcOptions): UnaryCall<UpdateScanTmplReq, UpdateScanTmplReply>;
    /**
     * @generated from protobuf rpc: DeleteScanTmpl(ada.DeleteScanTmplReq) returns (ada.DeleteScanTmplReply);
     */
    deleteScanTmpl(input: DeleteScanTmplReq, options?: RpcOptions): UnaryCall<DeleteScanTmplReq, DeleteScanTmplReply>;
    /**
     * @generated from protobuf rpc: AddScanTmpl(ada.AddScanTmplReq) returns (ada.AddScanTmplReply);
     */
    addScanTmpl(input: AddScanTmplReq, options?: RpcOptions): UnaryCall<AddScanTmplReq, AddScanTmplReply>;
    /**
     * @generated from protobuf rpc: ListScanPlugin(ada.ListScanPluginReq) returns (ada.ListScanPluginReply);
     */
    listScanPlugin(input: ListScanPluginReq, options?: RpcOptions): UnaryCall<ListScanPluginReq, ListScanPluginReply>;
    /**
     * 安全大盘
     *
     * @generated from protobuf rpc: DashboardStats(ada.DashboardStatsReq) returns (ada.DashboardStatsReply);
     */
    dashboardStats(input: DashboardStatsReq, options?: RpcOptions): UnaryCall<DashboardStatsReq, DashboardStatsReply>;
    /**
     * @generated from protobuf rpc: DashboardTrends(ada.DashboardTrendsReq) returns (ada.DashboardTrendsReply);
     */
    dashboardTrends(input: DashboardTrendsReq, options?: RpcOptions): UnaryCall<DashboardTrendsReq, DashboardTrendsReply>;
    /**
     * @generated from protobuf rpc: DashboardLogStats(ada.DashboardLogStatsReq) returns (ada.DashboardLogStatsReply);
     */
    dashboardLogStats(input: DashboardLogStatsReq, options?: RpcOptions): UnaryCall<DashboardLogStatsReq, DashboardLogStatsReply>;
}
// import "github.com/mwitkow/go-proto-validators/validator.proto";

/**
 * @generated from protobuf service ada.ADA
 */
export class ADAClient implements IADAClient, ServiceInfo {
    typeName = ADA.typeName;
    methods = ADA.methods;
    options = ADA.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * User 账户管理
     *
     * @generated from protobuf rpc: Login(ada.LoginReq) returns (ada.LoginReply);
     */
    login(input: LoginReq, options?: RpcOptions): UnaryCall<LoginReq, LoginReply> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginReq, LoginReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Logout(ada.LogoutReq) returns (ada.LogoutReply);
     */
    logout(input: LogoutReq, options?: RpcOptions): UnaryCall<LogoutReq, LogoutReply> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<LogoutReq, LogoutReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListUser(ada.ListUserReq) returns (ada.ListUserReply);
     */
    listUser(input: ListUserReq, options?: RpcOptions): UnaryCall<ListUserReq, ListUserReply> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListUserReq, ListUserReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddUser(ada.AddUserReq) returns (ada.AddUserReply);
     */
    addUser(input: AddUserReq, options?: RpcOptions): UnaryCall<AddUserReq, AddUserReply> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddUserReq, AddUserReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateUser(ada.UpdateUserReq) returns (ada.UpdateUserReply);
     */
    updateUser(input: UpdateUserReq, options?: RpcOptions): UnaryCall<UpdateUserReq, UpdateUserReply> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateUserReq, UpdateUserReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateUserPassword(ada.UpdateUserPasswordReq) returns (ada.UpdateUserPasswordReply);
     */
    updateUserPassword(input: UpdateUserPasswordReq, options?: RpcOptions): UnaryCall<UpdateUserPasswordReq, UpdateUserPasswordReply> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateUserPasswordReq, UpdateUserPasswordReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteUser(ada.DeleteUserReq) returns (ada.DeleteUserReply);
     */
    deleteUser(input: DeleteUserReq, options?: RpcOptions): UnaryCall<DeleteUserReq, DeleteUserReply> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteUserReq, DeleteUserReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UserExists(ada.UserExistsReq) returns (ada.UserExistsReply);
     */
    userExists(input: UserExistsReq, options?: RpcOptions): UnaryCall<UserExistsReq, UserExistsReply> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<UserExistsReq, UserExistsReply>("unary", this._transport, method, opt, input);
    }
    /**
     * Authority 二次验证相关接口
     *
     * @generated from protobuf rpc: CheckMfa(ada.CheckMfaReq) returns (ada.CheckMfaReply);
     */
    checkMfa(input: CheckMfaReq, options?: RpcOptions): UnaryCall<CheckMfaReq, CheckMfaReply> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<CheckMfaReq, CheckMfaReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: EnableMfa(ada.EnableMfaReq) returns (ada.EnableMfaReply);
     */
    enableMfa(input: EnableMfaReq, options?: RpcOptions): UnaryCall<EnableMfaReq, EnableMfaReply> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<EnableMfaReq, EnableMfaReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DisableMfa(ada.DisableMfaReq) returns (ada.DisableMfaReply);
     */
    disableMfa(input: DisableMfaReq, options?: RpcOptions): UnaryCall<DisableMfaReq, DisableMfaReply> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<DisableMfaReq, DisableMfaReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateAvatar(ada.UpdateAvatarReq) returns (ada.UpdateAvatarReply);
     */
    updateAvatar(input: UpdateAvatarReq, options?: RpcOptions): UnaryCall<UpdateAvatarReq, UpdateAvatarReply> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateAvatarReq, UpdateAvatarReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ResetPassword(ada.ResetPasswordReq) returns (ada.ResetPasswordReply);
     */
    resetPassword(input: ResetPasswordReq, options?: RpcOptions): UnaryCall<ResetPasswordReq, ResetPasswordReply> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<ResetPasswordReq, ResetPasswordReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPwdUpdateTm(ada.GetPwdUpdateTmReq) returns (ada.GetPwdUpdateTmReply);
     */
    getPwdUpdateTm(input: GetPwdUpdateTmReq, options?: RpcOptions): UnaryCall<GetPwdUpdateTmReq, GetPwdUpdateTmReply> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPwdUpdateTmReq, GetPwdUpdateTmReply>("unary", this._transport, method, opt, input);
    }
    /**
     * Domain
     *
     * @generated from protobuf rpc: ListDomain(ada.ListDomainReq) returns (ada.ListDomainReply);
     */
    listDomain(input: ListDomainReq, options?: RpcOptions): UnaryCall<ListDomainReq, ListDomainReply> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListDomainReq, ListDomainReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddDomain(ada.AddDomainReq) returns (ada.AddDomainReply);
     */
    addDomain(input: AddDomainReq, options?: RpcOptions): UnaryCall<AddDomainReq, AddDomainReply> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddDomainReq, AddDomainReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: TestDomain(ada.TestDomainReq) returns (ada.TestDomainReply);
     */
    testDomain(input: TestDomainReq, options?: RpcOptions): UnaryCall<TestDomainReq, TestDomainReply> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return stackIntercept<TestDomainReq, TestDomainReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateDomain(ada.UpdateDomainReq) returns (ada.UpdateDomainReply);
     */
    updateDomain(input: UpdateDomainReq, options?: RpcOptions): UnaryCall<UpdateDomainReq, UpdateDomainReply> {
        const method = this.methods[17], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateDomainReq, UpdateDomainReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteDomain(ada.DeleteDomainReq) returns (ada.DeleteDomainReply);
     */
    deleteDomain(input: DeleteDomainReq, options?: RpcOptions): UnaryCall<DeleteDomainReq, DeleteDomainReply> {
        const method = this.methods[18], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteDomainReq, DeleteDomainReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateDomainData(ada.UpdateDomainDataReq) returns (ada.UpdateDomainDataReply);
     */
    updateDomainData(input: UpdateDomainDataReq, options?: RpcOptions): UnaryCall<UpdateDomainDataReq, UpdateDomainDataReply> {
        const method = this.methods[19], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateDomainDataReq, UpdateDomainDataReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeploySensor(ada.DeploySensorReq) returns (ada.DeploySensorReply);
     */
    deploySensor(input: DeploySensorReq, options?: RpcOptions): UnaryCall<DeploySensorReq, DeploySensorReply> {
        const method = this.methods[20], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeploySensorReq, DeploySensorReply>("unary", this._transport, method, opt, input);
    }
    /**
     * sensor
     *
     * @generated from protobuf rpc: ListSensor(ada.ListSensorReq) returns (ada.ListSensorReply);
     */
    listSensor(input: ListSensorReq, options?: RpcOptions): UnaryCall<ListSensorReq, ListSensorReply> {
        const method = this.methods[21], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListSensorReq, ListSensorReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateSensor(ada.UpdateSensorReq) returns (ada.UpdateSensorReply);
     */
    updateSensor(input: UpdateSensorReq, options?: RpcOptions): UnaryCall<UpdateSensorReq, UpdateSensorReply> {
        const method = this.methods[22], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateSensorReq, UpdateSensorReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DownloadSensor(ada.DownloadSensorReq) returns (ada.DownloadSensorReply);
     */
    downloadSensor(input: DownloadSensorReq, options?: RpcOptions): UnaryCall<DownloadSensorReq, DownloadSensorReply> {
        const method = this.methods[23], opt = this._transport.mergeOptions(options);
        return stackIntercept<DownloadSensorReq, DownloadSensorReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CmdSensor(ada.CmdSensorReq) returns (ada.CmdSensorReply);
     */
    cmdSensor(input: CmdSensorReq, options?: RpcOptions): UnaryCall<CmdSensorReq, CmdSensorReply> {
        const method = this.methods[24], opt = this._transport.mergeOptions(options);
        return stackIntercept<CmdSensorReq, CmdSensorReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateSensorVersion(ada.UpdateSensorVersionReq) returns (ada.UpdateSensorVersionReply);
     */
    updateSensorVersion(input: UpdateSensorVersionReq, options?: RpcOptions): UnaryCall<UpdateSensorVersionReq, UpdateSensorVersionReply> {
        const method = this.methods[25], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateSensorVersionReq, UpdateSensorVersionReply>("unary", this._transport, method, opt, input);
    }
    /**
     * 系统信息
     * 1.基本信息
     *
     * @generated from protobuf rpc: GetSystemInfo(ada.GetSystemInfoReq) returns (ada.GetSystemInfoReply);
     */
    getSystemInfo(input: GetSystemInfoReq, options?: RpcOptions): UnaryCall<GetSystemInfoReq, GetSystemInfoReply> {
        const method = this.methods[26], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetSystemInfoReq, GetSystemInfoReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetSystemIcon(ada.GetSystemIconReq) returns (ada.GetSystemIconReply);
     */
    getSystemIcon(input: GetSystemIconReq, options?: RpcOptions): UnaryCall<GetSystemIconReq, GetSystemIconReply> {
        const method = this.methods[27], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetSystemIconReq, GetSystemIconReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateSystemLanguage(ada.UpdateSystemLanguageReq) returns (ada.UpdateSystemLanguageReply);
     */
    updateSystemLanguage(input: UpdateSystemLanguageReq, options?: RpcOptions): UnaryCall<UpdateSystemLanguageReq, UpdateSystemLanguageReply> {
        const method = this.methods[28], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateSystemLanguageReq, UpdateSystemLanguageReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateSystemCfg(ada.UpdateSystemCfgReq) returns (ada.UpdateSystemCfgReply);
     */
    updateSystemCfg(input: UpdateSystemCfgReq, options?: RpcOptions): UnaryCall<UpdateSystemCfgReq, UpdateSystemCfgReply> {
        const method = this.methods[29], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateSystemCfgReq, UpdateSystemCfgReply>("unary", this._transport, method, opt, input);
    }
    /**
     * 2.系统监控: load|cpu|mem|net_rx|net_tx
     *
     * @generated from protobuf rpc: GetSystemStats(ada.GetSystemStatsReq) returns (ada.GetSystemStatsReply);
     */
    getSystemStats(input: GetSystemStatsReq, options?: RpcOptions): UnaryCall<GetSystemStatsReq, GetSystemStatsReply> {
        const method = this.methods[30], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetSystemStatsReq, GetSystemStatsReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetSystemStatsCfg(ada.SetSystemStatsCfgReq) returns (ada.SetSystemStatsCfgReply);
     */
    setSystemStatsCfg(input: SetSystemStatsCfgReq, options?: RpcOptions): UnaryCall<SetSystemStatsCfgReq, SetSystemStatsCfgReply> {
        const method = this.methods[31], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetSystemStatsCfgReq, SetSystemStatsCfgReply>("unary", this._transport, method, opt, input);
    }
    /**
     * 3.授权管理
     *
     * @generated from protobuf rpc: GetLicense(ada.GetLicenseReq) returns (ada.GetLicenseReply);
     */
    getLicense(input: GetLicenseReq, options?: RpcOptions): UnaryCall<GetLicenseReq, GetLicenseReply> {
        const method = this.methods[32], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetLicenseReq, GetLicenseReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateLicense(ada.UpdateLicenseReq) returns (ada.UpdateLicenseReply);
     */
    updateLicense(input: UpdateLicenseReq, options?: RpcOptions): UnaryCall<UpdateLicenseReq, UpdateLicenseReply> {
        const method = this.methods[33], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateLicenseReq, UpdateLicenseReply>("unary", this._transport, method, opt, input);
    }
    /**
     * 4.调试工具
     *
     * @generated from protobuf rpc: NetworkDebug(ada.NetworkDebugReq) returns (ada.NetworkDebugReply);
     */
    networkDebug(input: NetworkDebugReq, options?: RpcOptions): UnaryCall<NetworkDebugReq, NetworkDebugReply> {
        const method = this.methods[34], opt = this._transport.mergeOptions(options);
        return stackIntercept<NetworkDebugReq, NetworkDebugReply>("unary", this._transport, method, opt, input);
    }
    /**
     * 告警配置
     *
     * @generated from protobuf rpc: ListNotifyConf(ada.ListNotifyConfReq) returns (ada.ListNotifyConfReply);
     */
    listNotifyConf(input: ListNotifyConfReq, options?: RpcOptions): UnaryCall<ListNotifyConfReq, ListNotifyConfReply> {
        const method = this.methods[35], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListNotifyConfReq, ListNotifyConfReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateNotifyConf(ada.UpdateNotifyConfReq) returns (ada.UpdateNotifyConfReply);
     */
    updateNotifyConf(input: UpdateNotifyConfReq, options?: RpcOptions): UnaryCall<UpdateNotifyConfReq, UpdateNotifyConfReply> {
        const method = this.methods[36], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateNotifyConfReq, UpdateNotifyConfReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: EnableNotifyConf(ada.EnableNotifyConfReq) returns (ada.EnableNotifyConfReply);
     */
    enableNotifyConf(input: EnableNotifyConfReq, options?: RpcOptions): UnaryCall<EnableNotifyConfReq, EnableNotifyConfReply> {
        const method = this.methods[37], opt = this._transport.mergeOptions(options);
        return stackIntercept<EnableNotifyConfReq, EnableNotifyConfReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: TestNotifyConf(ada.TestNotifyConfReq) returns (ada.TestNotifyConfReply);
     */
    testNotifyConf(input: TestNotifyConfReq, options?: RpcOptions): UnaryCall<TestNotifyConfReq, TestNotifyConfReply> {
        const method = this.methods[38], opt = this._transport.mergeOptions(options);
        return stackIntercept<TestNotifyConfReq, TestNotifyConfReply>("unary", this._transport, method, opt, input);
    }
    /**
     * 导出管理
     *
     * @generated from protobuf rpc: ListExportTask(ada.ListExportTaskReq) returns (ada.ListExportTaskReply);
     */
    listExportTask(input: ListExportTaskReq, options?: RpcOptions): UnaryCall<ListExportTaskReq, ListExportTaskReply> {
        const method = this.methods[39], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListExportTaskReq, ListExportTaskReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddExportTask(ada.AddExportTaskReq) returns (ada.AddExportTaskReply);
     */
    addExportTask(input: AddExportTaskReq, options?: RpcOptions): UnaryCall<AddExportTaskReq, AddExportTaskReply> {
        const method = this.methods[40], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddExportTaskReq, AddExportTaskReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteExportTask(ada.DeleteExportTaskReq) returns (ada.DeleteExportTaskReply);
     */
    deleteExportTask(input: DeleteExportTaskReq, options?: RpcOptions): UnaryCall<DeleteExportTaskReq, DeleteExportTaskReply> {
        const method = this.methods[41], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteExportTaskReq, DeleteExportTaskReply>("unary", this._transport, method, opt, input);
    }
    /**
     * 消息中心
     *
     * @generated from protobuf rpc: ListNotify(ada.ListNotifyReq) returns (ada.ListNotifyReply);
     */
    listNotify(input: ListNotifyReq, options?: RpcOptions): UnaryCall<ListNotifyReq, ListNotifyReply> {
        const method = this.methods[42], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListNotifyReq, ListNotifyReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateNotify(ada.UpdateNotifyReq) returns (ada.UpdateNotifyReply);
     */
    updateNotify(input: UpdateNotifyReq, options?: RpcOptions): UnaryCall<UpdateNotifyReq, UpdateNotifyReply> {
        const method = this.methods[43], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateNotifyReq, UpdateNotifyReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: StatsNotify(ada.StatsNotifyReq) returns (ada.StatsNotifyReply);
     */
    statsNotify(input: StatsNotifyReq, options?: RpcOptions): UnaryCall<StatsNotifyReq, StatsNotifyReply> {
        const method = this.methods[44], opt = this._transport.mergeOptions(options);
        return stackIntercept<StatsNotifyReq, StatsNotifyReply>("unary", this._transport, method, opt, input);
    }
    /**
     * 日志审计
     *
     * @generated from protobuf rpc: ListAuditLog(ada.ListAuditLogReq) returns (ada.ListAuditLogReply);
     */
    listAuditLog(input: ListAuditLogReq, options?: RpcOptions): UnaryCall<ListAuditLogReq, ListAuditLogReply> {
        const method = this.methods[45], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAuditLogReq, ListAuditLogReply>("unary", this._transport, method, opt, input);
    }
    /**
     * 系统日志
     *
     * @generated from protobuf rpc: ListSystemLogs(ada.ListSystemLogsReq) returns (ada.ListSystemLogsReply);
     */
    listSystemLogs(input: ListSystemLogsReq, options?: RpcOptions): UnaryCall<ListSystemLogsReq, ListSystemLogsReply> {
        const method = this.methods[46], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListSystemLogsReq, ListSystemLogsReply>("unary", this._transport, method, opt, input);
    }
    /**
     * //////////////////////////////
     * threat威胁检测dashboard
     *
     * @generated from protobuf rpc: ThreatTops(ada.ThreatTopsReq) returns (ada.ThreatTopsReply);
     */
    threatTops(input: ThreatTopsReq, options?: RpcOptions): UnaryCall<ThreatTopsReq, ThreatTopsReply> {
        const method = this.methods[47], opt = this._transport.mergeOptions(options);
        return stackIntercept<ThreatTopsReq, ThreatTopsReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ThreatTrends(ada.ThreatTrendsReq) returns (ada.ThreatTrendsReply);
     */
    threatTrends(input: ThreatTrendsReq, options?: RpcOptions): UnaryCall<ThreatTrendsReq, ThreatTrendsReply> {
        const method = this.methods[48], opt = this._transport.mergeOptions(options);
        return stackIntercept<ThreatTrendsReq, ThreatTrendsReply>("unary", this._transport, method, opt, input);
    }
    /**
     * threat威胁检测
     *
     * @generated from protobuf rpc: ListThreat(ada.ListThreatReq) returns (ada.ListThreatReply);
     */
    listThreat(input: ListThreatReq, options?: RpcOptions): UnaryCall<ListThreatReq, ListThreatReply> {
        const method = this.methods[49], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListThreatReq, ListThreatReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetThreatNames(ada.GetThreatNamesReq) returns (ada.GetThreatNamesReply);
     */
    getThreatNames(input: GetThreatNamesReq, options?: RpcOptions): UnaryCall<GetThreatNamesReq, GetThreatNamesReply> {
        const method = this.methods[50], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetThreatNamesReq, GetThreatNamesReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetThreat(ada.GetThreatReq) returns (ada.GetThreatReply);
     */
    getThreat(input: GetThreatReq, options?: RpcOptions): UnaryCall<GetThreatReq, GetThreatReply> {
        const method = this.methods[51], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetThreatReq, GetThreatReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ActionThreat(ada.ActionThreatReq) returns (ada.ActionThreatReply);
     */
    actionThreat(input: ActionThreatReq, options?: RpcOptions): UnaryCall<ActionThreatReq, ActionThreatReply> {
        const method = this.methods[52], opt = this._transport.mergeOptions(options);
        return stackIntercept<ActionThreatReq, ActionThreatReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListActivity(ada.ListActivityReq) returns (ada.ListActivityReply);
     */
    listActivity(input: ListActivityReq, options?: RpcOptions): UnaryCall<ListActivityReq, ListActivityReply> {
        const method = this.methods[53], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListActivityReq, ListActivityReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetActivityNames(ada.GetActivityNamesReq) returns (ada.GetActivityNamesReply);
     */
    getActivityNames(input: GetActivityNamesReq, options?: RpcOptions): UnaryCall<GetActivityNamesReq, GetActivityNamesReply> {
        const method = this.methods[54], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetActivityNamesReq, GetActivityNamesReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetActivity(ada.GetActivityReq) returns (ada.GetActivityReply);
     */
    getActivity(input: GetActivityReq, options?: RpcOptions): UnaryCall<GetActivityReq, GetActivityReply> {
        const method = this.methods[55], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetActivityReq, GetActivityReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListSensitiveEntry(ada.ListSensitiveEntryReq) returns (ada.ListSensitiveEntryReply);
     */
    listSensitiveEntry(input: ListSensitiveEntryReq, options?: RpcOptions): UnaryCall<ListSensitiveEntryReq, ListSensitiveEntryReply> {
        const method = this.methods[56], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListSensitiveEntryReq, ListSensitiveEntryReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddSensitiveEntry(ada.AddSensitiveEntryReq) returns (ada.AddSensitiveEntryReply);
     */
    addSensitiveEntry(input: AddSensitiveEntryReq, options?: RpcOptions): UnaryCall<AddSensitiveEntryReq, AddSensitiveEntryReply> {
        const method = this.methods[57], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddSensitiveEntryReq, AddSensitiveEntryReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListDomainEntry(ada.ListDomainEntryReq) returns (ada.ListDomainEntryReply);
     */
    listDomainEntry(input: ListDomainEntryReq, options?: RpcOptions): UnaryCall<ListDomainEntryReq, ListDomainEntryReply> {
        const method = this.methods[58], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListDomainEntryReq, ListDomainEntryReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteSensitiveEntry(ada.DeleteSensitiveEntryReq) returns (ada.DeleteSensitiveEntryReply);
     */
    deleteSensitiveEntry(input: DeleteSensitiveEntryReq, options?: RpcOptions): UnaryCall<DeleteSensitiveEntryReq, DeleteSensitiveEntryReply> {
        const method = this.methods[59], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteSensitiveEntryReq, DeleteSensitiveEntryReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListThreatWhitelist(ada.ListThreatWhitelistReq) returns (ada.ListThreatWhitelistReply);
     */
    listThreatWhitelist(input: ListThreatWhitelistReq, options?: RpcOptions): UnaryCall<ListThreatWhitelistReq, ListThreatWhitelistReply> {
        const method = this.methods[60], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListThreatWhitelistReq, ListThreatWhitelistReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetThreatWhitelistField(ada.GetThreatWhitelistFieldReq) returns (ada.GetThreatWhitelistFieldReply);
     */
    getThreatWhitelistField(input: GetThreatWhitelistFieldReq, options?: RpcOptions): UnaryCall<GetThreatWhitelistFieldReq, GetThreatWhitelistFieldReply> {
        const method = this.methods[61], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetThreatWhitelistFieldReq, GetThreatWhitelistFieldReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddThreatWhitelist(ada.AddThreatWhitelistReq) returns (ada.AddThreatWhitelistReply);
     */
    addThreatWhitelist(input: AddThreatWhitelistReq, options?: RpcOptions): UnaryCall<AddThreatWhitelistReq, AddThreatWhitelistReply> {
        const method = this.methods[62], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddThreatWhitelistReq, AddThreatWhitelistReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateThreatWhitelist(ada.UpdateThreatWhitelistReq) returns (ada.UpdateThreatWhitelistReply);
     */
    updateThreatWhitelist(input: UpdateThreatWhitelistReq, options?: RpcOptions): UnaryCall<UpdateThreatWhitelistReq, UpdateThreatWhitelistReply> {
        const method = this.methods[63], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateThreatWhitelistReq, UpdateThreatWhitelistReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteThreatWhitelist(ada.DeleteThreatWhitelistReq) returns (ada.DeleteThreatWhitelistReply);
     */
    deleteThreatWhitelist(input: DeleteThreatWhitelistReq, options?: RpcOptions): UnaryCall<DeleteThreatWhitelistReq, DeleteThreatWhitelistReply> {
        const method = this.methods[64], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteThreatWhitelistReq, DeleteThreatWhitelistReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListThreatBlock(ada.ListThreatBlockReq) returns (ada.ListThreatBlockReply);
     */
    listThreatBlock(input: ListThreatBlockReq, options?: RpcOptions): UnaryCall<ListThreatBlockReq, ListThreatBlockReply> {
        const method = this.methods[65], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListThreatBlockReq, ListThreatBlockReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddThreatBlock(ada.AddThreatBlockReq) returns (ada.AddThreatBlockReply);
     */
    addThreatBlock(input: AddThreatBlockReq, options?: RpcOptions): UnaryCall<AddThreatBlockReq, AddThreatBlockReply> {
        const method = this.methods[66], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddThreatBlockReq, AddThreatBlockReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateThreatBlock(ada.UpdateThreatBlockReq) returns (ada.UpdateThreatBlockReply);
     */
    updateThreatBlock(input: UpdateThreatBlockReq, options?: RpcOptions): UnaryCall<UpdateThreatBlockReq, UpdateThreatBlockReply> {
        const method = this.methods[67], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateThreatBlockReq, UpdateThreatBlockReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteThreatBlock(ada.DeleteThreatBlockReq) returns (ada.DeleteThreatBlockReply);
     */
    deleteThreatBlock(input: DeleteThreatBlockReq, options?: RpcOptions): UnaryCall<DeleteThreatBlockReq, DeleteThreatBlockReply> {
        const method = this.methods[68], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteThreatBlockReq, DeleteThreatBlockReply>("unary", this._transport, method, opt, input);
    }
    /**
     * Rule Management (Alert Rules & Activity Rules)
     *
     * @generated from protobuf rpc: ListAlertRule(ada.ListAlertRuleReq) returns (ada.ListAlertRuleReply);
     */
    listAlertRule(input: ListAlertRuleReq, options?: RpcOptions): UnaryCall<ListAlertRuleReq, ListAlertRuleReply> {
        const method = this.methods[69], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAlertRuleReq, ListAlertRuleReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddAlertRule(ada.AddAlertRuleReq) returns (ada.AddAlertRuleReply);
     */
    addAlertRule(input: AddAlertRuleReq, options?: RpcOptions): UnaryCall<AddAlertRuleReq, AddAlertRuleReply> {
        const method = this.methods[70], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddAlertRuleReq, AddAlertRuleReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateAlertRule(ada.UpdateAlertRuleReq) returns (ada.UpdateAlertRuleReply);
     */
    updateAlertRule(input: UpdateAlertRuleReq, options?: RpcOptions): UnaryCall<UpdateAlertRuleReq, UpdateAlertRuleReply> {
        const method = this.methods[71], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateAlertRuleReq, UpdateAlertRuleReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteAlertRule(ada.DeleteAlertRuleReq) returns (ada.DeleteAlertRuleReply);
     */
    deleteAlertRule(input: DeleteAlertRuleReq, options?: RpcOptions): UnaryCall<DeleteAlertRuleReq, DeleteAlertRuleReply> {
        const method = this.methods[72], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteAlertRuleReq, DeleteAlertRuleReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAlertRuleNames(ada.GetAlertRuleNamesReq) returns (ada.GetAlertRuleNamesReply);
     */
    getAlertRuleNames(input: GetAlertRuleNamesReq, options?: RpcOptions): UnaryCall<GetAlertRuleNamesReq, GetAlertRuleNamesReply> {
        const method = this.methods[73], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAlertRuleNamesReq, GetAlertRuleNamesReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAlertTypes(ada.GetAlertTypesReq) returns (ada.GetAlertTypesReply);
     */
    getAlertTypes(input: GetAlertTypesReq, options?: RpcOptions): UnaryCall<GetAlertTypesReq, GetAlertTypesReply> {
        const method = this.methods[74], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAlertTypesReq, GetAlertTypesReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAlertRuleTags(ada.GetAlertRuleTagsReq) returns (ada.GetAlertRuleTagsReply);
     */
    getAlertRuleTags(input: GetAlertRuleTagsReq, options?: RpcOptions): UnaryCall<GetAlertRuleTagsReq, GetAlertRuleTagsReply> {
        const method = this.methods[75], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAlertRuleTagsReq, GetAlertRuleTagsReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListActivityRule(ada.ListActivityRuleReq) returns (ada.ListActivityRuleReply);
     */
    listActivityRule(input: ListActivityRuleReq, options?: RpcOptions): UnaryCall<ListActivityRuleReq, ListActivityRuleReply> {
        const method = this.methods[76], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListActivityRuleReq, ListActivityRuleReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetActivityRule(ada.GetActivityRuleReq) returns (ada.GetActivityRuleReply);
     */
    getActivityRule(input: GetActivityRuleReq, options?: RpcOptions): UnaryCall<GetActivityRuleReq, GetActivityRuleReply> {
        const method = this.methods[77], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetActivityRuleReq, GetActivityRuleReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddActivityRule(ada.AddActivityRuleReq) returns (ada.AddActivityRuleReply);
     */
    addActivityRule(input: AddActivityRuleReq, options?: RpcOptions): UnaryCall<AddActivityRuleReq, AddActivityRuleReply> {
        const method = this.methods[78], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddActivityRuleReq, AddActivityRuleReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateActivityRule(ada.UpdateActivityRuleReq) returns (ada.UpdateActivityRuleReply);
     */
    updateActivityRule(input: UpdateActivityRuleReq, options?: RpcOptions): UnaryCall<UpdateActivityRuleReq, UpdateActivityRuleReply> {
        const method = this.methods[79], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateActivityRuleReq, UpdateActivityRuleReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteActivityRule(ada.DeleteActivityRuleReq) returns (ada.DeleteActivityRuleReply);
     */
    deleteActivityRule(input: DeleteActivityRuleReq, options?: RpcOptions): UnaryCall<DeleteActivityRuleReq, DeleteActivityRuleReply> {
        const method = this.methods[80], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteActivityRuleReq, DeleteActivityRuleReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetActivityRuleFields(ada.GetActivityRuleFieldsReq) returns (ada.GetActivityRuleFieldsReply);
     */
    getActivityRuleFields(input: GetActivityRuleFieldsReq, options?: RpcOptions): UnaryCall<GetActivityRuleFieldsReq, GetActivityRuleFieldsReply> {
        const method = this.methods[81], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetActivityRuleFieldsReq, GetActivityRuleFieldsReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetActivityRuleUniqueFields(ada.GetActivityRuleUniqueFieldsReq) returns (ada.GetActivityRuleUniqueFieldsReply);
     */
    getActivityRuleUniqueFields(input: GetActivityRuleUniqueFieldsReq, options?: RpcOptions): UnaryCall<GetActivityRuleUniqueFieldsReq, GetActivityRuleUniqueFieldsReply> {
        const method = this.methods[82], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetActivityRuleUniqueFieldsReq, GetActivityRuleUniqueFieldsReply>("unary", this._transport, method, opt, input);
    }
    /**
     * //////////////////////////////
     * scanrisk主动检测dashboard
     *
     * @generated from protobuf rpc: ScanRiskStats(ada.ScanRiskStatsReq) returns (ada.ScanRiskStatsReply);
     */
    scanRiskStats(input: ScanRiskStatsReq, options?: RpcOptions): UnaryCall<ScanRiskStatsReq, ScanRiskStatsReply> {
        const method = this.methods[83], opt = this._transport.mergeOptions(options);
        return stackIntercept<ScanRiskStatsReq, ScanRiskStatsReply>("unary", this._transport, method, opt, input);
    }
    /**
     * scanrisk主动检测
     *
     * @generated from protobuf rpc: ListBaseline(ada.ListBaselineReq) returns (ada.ListBaselineReply);
     */
    listBaseline(input: ListBaselineReq, options?: RpcOptions): UnaryCall<ListBaselineReq, ListBaselineReply> {
        const method = this.methods[84], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListBaselineReq, ListBaselineReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetBaseline(ada.GetBaselineReq) returns (ada.GetBaselineReply);
     */
    getBaseline(input: GetBaselineReq, options?: RpcOptions): UnaryCall<GetBaselineReq, GetBaselineReply> {
        const method = this.methods[85], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBaselineReq, GetBaselineReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListLeak(ada.ListLeakReq) returns (ada.ListLeakReply);
     */
    listLeak(input: ListLeakReq, options?: RpcOptions): UnaryCall<ListLeakReq, ListLeakReply> {
        const method = this.methods[86], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListLeakReq, ListLeakReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListWeakPwd(ada.ListWeakPwdReq) returns (ada.ListWeakPwdReply);
     */
    listWeakPwd(input: ListWeakPwdReq, options?: RpcOptions): UnaryCall<ListWeakPwdReq, ListWeakPwdReply> {
        const method = this.methods[87], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListWeakPwdReq, ListWeakPwdReply>("unary", this._transport, method, opt, input);
    }
    /**
     * 任务管理
     *
     * @generated from protobuf rpc: ListScanTask(ada.ListScanTaskReq) returns (ada.ListScanTaskReply);
     */
    listScanTask(input: ListScanTaskReq, options?: RpcOptions): UnaryCall<ListScanTaskReq, ListScanTaskReply> {
        const method = this.methods[88], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListScanTaskReq, ListScanTaskReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetScanTask(ada.GetScanTaskReq) returns (ada.GetScanTaskReply);
     */
    getScanTask(input: GetScanTaskReq, options?: RpcOptions): UnaryCall<GetScanTaskReq, GetScanTaskReply> {
        const method = this.methods[89], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetScanTaskReq, GetScanTaskReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddScanTask(ada.AddScanTaskReq) returns (ada.AddScanTaskReply);
     */
    addScanTask(input: AddScanTaskReq, options?: RpcOptions): UnaryCall<AddScanTaskReq, AddScanTaskReply> {
        const method = this.methods[90], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddScanTaskReq, AddScanTaskReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RecheckScanTask(ada.RecheckScanTaskReq) returns (ada.RecheckScanTaskReply);
     */
    recheckScanTask(input: RecheckScanTaskReq, options?: RpcOptions): UnaryCall<RecheckScanTaskReq, RecheckScanTaskReply> {
        const method = this.methods[91], opt = this._transport.mergeOptions(options);
        return stackIntercept<RecheckScanTaskReq, RecheckScanTaskReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteScanTask(ada.DeleteScanTaskReq) returns (ada.DeleteScanTaskReply);
     */
    deleteScanTask(input: DeleteScanTaskReq, options?: RpcOptions): UnaryCall<DeleteScanTaskReq, DeleteScanTaskReply> {
        const method = this.methods[92], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteScanTaskReq, DeleteScanTaskReply>("unary", this._transport, method, opt, input);
    }
    /**
     * 扫描配置
     *
     * @generated from protobuf rpc: ListScanConf(ada.ListScanConfReq) returns (ada.ListScanConfReply);
     */
    listScanConf(input: ListScanConfReq, options?: RpcOptions): UnaryCall<ListScanConfReq, ListScanConfReply> {
        const method = this.methods[93], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListScanConfReq, ListScanConfReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SetScanConf(ada.SetScanConfReq) returns (ada.SetScanConfReply);
     */
    setScanConf(input: SetScanConfReq, options?: RpcOptions): UnaryCall<SetScanConfReq, SetScanConfReply> {
        const method = this.methods[94], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetScanConfReq, SetScanConfReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetScanConf(ada.GetScanConfReq) returns (ada.GetScanConfReply);
     */
    getScanConf(input: GetScanConfReq, options?: RpcOptions): UnaryCall<GetScanConfReq, GetScanConfReply> {
        const method = this.methods[95], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetScanConfReq, GetScanConfReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetScanTmplNames(ada.GetScanTmplNamesReq) returns (ada.GetScanTmplNamesReply);
     */
    getScanTmplNames(input: GetScanTmplNamesReq, options?: RpcOptions): UnaryCall<GetScanTmplNamesReq, GetScanTmplNamesReply> {
        const method = this.methods[96], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetScanTmplNamesReq, GetScanTmplNamesReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateScanConf(ada.UpdateScanConfReq) returns (ada.UpdateScanConfReply);
     */
    updateScanConf(input: UpdateScanConfReq, options?: RpcOptions): UnaryCall<UpdateScanConfReq, UpdateScanConfReply> {
        const method = this.methods[97], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateScanConfReq, UpdateScanConfReply>("unary", this._transport, method, opt, input);
    }
    /**
     * 扫描模板
     *
     * @generated from protobuf rpc: ListScanTmpl(ada.ListScanTmplReq) returns (ada.ListScanTmplReply);
     */
    listScanTmpl(input: ListScanTmplReq, options?: RpcOptions): UnaryCall<ListScanTmplReq, ListScanTmplReply> {
        const method = this.methods[98], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListScanTmplReq, ListScanTmplReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetScanTmpl(ada.GetScanTmplReq) returns (ada.GetScanTmplReply);
     */
    getScanTmpl(input: GetScanTmplReq, options?: RpcOptions): UnaryCall<GetScanTmplReq, GetScanTmplReply> {
        const method = this.methods[99], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetScanTmplReq, GetScanTmplReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateScanTmpl(ada.UpdateScanTmplReq) returns (ada.UpdateScanTmplReply);
     */
    updateScanTmpl(input: UpdateScanTmplReq, options?: RpcOptions): UnaryCall<UpdateScanTmplReq, UpdateScanTmplReply> {
        const method = this.methods[100], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateScanTmplReq, UpdateScanTmplReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteScanTmpl(ada.DeleteScanTmplReq) returns (ada.DeleteScanTmplReply);
     */
    deleteScanTmpl(input: DeleteScanTmplReq, options?: RpcOptions): UnaryCall<DeleteScanTmplReq, DeleteScanTmplReply> {
        const method = this.methods[101], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteScanTmplReq, DeleteScanTmplReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddScanTmpl(ada.AddScanTmplReq) returns (ada.AddScanTmplReply);
     */
    addScanTmpl(input: AddScanTmplReq, options?: RpcOptions): UnaryCall<AddScanTmplReq, AddScanTmplReply> {
        const method = this.methods[102], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddScanTmplReq, AddScanTmplReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListScanPlugin(ada.ListScanPluginReq) returns (ada.ListScanPluginReply);
     */
    listScanPlugin(input: ListScanPluginReq, options?: RpcOptions): UnaryCall<ListScanPluginReq, ListScanPluginReply> {
        const method = this.methods[103], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListScanPluginReq, ListScanPluginReply>("unary", this._transport, method, opt, input);
    }
    /**
     * 安全大盘
     *
     * @generated from protobuf rpc: DashboardStats(ada.DashboardStatsReq) returns (ada.DashboardStatsReply);
     */
    dashboardStats(input: DashboardStatsReq, options?: RpcOptions): UnaryCall<DashboardStatsReq, DashboardStatsReply> {
        const method = this.methods[104], opt = this._transport.mergeOptions(options);
        return stackIntercept<DashboardStatsReq, DashboardStatsReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DashboardTrends(ada.DashboardTrendsReq) returns (ada.DashboardTrendsReply);
     */
    dashboardTrends(input: DashboardTrendsReq, options?: RpcOptions): UnaryCall<DashboardTrendsReq, DashboardTrendsReply> {
        const method = this.methods[105], opt = this._transport.mergeOptions(options);
        return stackIntercept<DashboardTrendsReq, DashboardTrendsReply>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DashboardLogStats(ada.DashboardLogStatsReq) returns (ada.DashboardLogStatsReply);
     */
    dashboardLogStats(input: DashboardLogStatsReq, options?: RpcOptions): UnaryCall<DashboardLogStatsReq, DashboardLogStatsReply> {
        const method = this.methods[106], opt = this._transport.mergeOptions(options);
        return stackIntercept<DashboardLogStatsReq, DashboardLogStatsReply>("unary", this._transport, method, opt, input);
    }
}
